namespace PiSignalWatch.Storage; using System.Text.Json; using PiSignalWatch.Config; using PiSignalWatch.Models; using Microsoft.Extensions.Options;
public interface IStorageProvider{Task SaveRawItemsAsync(string source,IReadOnlyCollection<SourceItem> items,CancellationToken ct); Task SaveProcessedItemsAsync(IReadOnlyCollection<ProcessedItem> items,CancellationToken ct); Task SaveDigestAsync(Digest digest,CancellationToken ct);} 
public class JsonFileStorageProvider(IOptions<AppSettings> o):IStorageProvider{string Root=>o.Value.DataFolder; static readonly JsonSerializerOptions J=new(){WriteIndented=true};
public Task SaveRawItemsAsync(string source,IReadOnlyCollection<SourceItem> items,CancellationToken ct)=>Write(Path.Combine(Root,"raw",source,$"{DateTime.UtcNow:yyyyMMddHHmmss}.json"),items,ct);
public Task SaveProcessedItemsAsync(IReadOnlyCollection<ProcessedItem> items,CancellationToken ct)=>Write(Path.Combine(Root,"processed",$"{DateTime.UtcNow:yyyyMMddHHmmss}.json"),items,ct);
public Task SaveDigestAsync(Digest d,CancellationToken ct)=>Write(Path.Combine(Root,"digests",$"{DateTime.UtcNow:yyyyMMddHHmmss}.json"),d,ct);
static async Task Write<T>(string p,T obj,CancellationToken ct){Directory.CreateDirectory(Path.GetDirectoryName(p)!); await File.WriteAllTextAsync(p,JsonSerializer.Serialize(obj,J),ct);} }
public class StateStore(IOptions<AppSettings> o){string Root=>Path.Combine(o.Value.DataFolder,"state");
public async Task<HashSet<string>> LoadSeenItemsAsync(CancellationToken ct){var p=Path.Combine(Root,"seen-items.json"); if(!File.Exists(p)) return new(); return JsonSerializer.Deserialize<HashSet<string>>(await File.ReadAllTextAsync(p,ct))??new();}
public async Task SaveSeenItemsAsync(HashSet<string> s,CancellationToken ct){Directory.CreateDirectory(Root); await File.WriteAllTextAsync(Path.Combine(Root,"seen-items.json"),JsonSerializer.Serialize(s),ct);} 
public async Task<Dictionary<string,string>> LoadCollectorStateAsync(CancellationToken ct){var p=Path.Combine(Root,"collector-state.json"); if(!File.Exists(p)) return new(); return JsonSerializer.Deserialize<Dictionary<string,string>>(await File.ReadAllTextAsync(p,ct))??new();}
public async Task SaveCollectorStateAsync(Dictionary<string,string> s,CancellationToken ct){Directory.CreateDirectory(Root); await File.WriteAllTextAsync(Path.Combine(Root,"collector-state.json"),JsonSerializer.Serialize(s),ct);} }
